# SOURCE: https://install.portworx.com/?operator=true&mc=false&kbver=1.21.0&b=true&s=%2Fdev%2Fsdb%2C%2Fdev%2Fsdc&j=auto&kd=%2Fdev%2Fsdd&c=px-cluster-0276bc75-861a-4c2b-b798-3f4020bbad18&stork=true&st=k8s
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-0276bc75-861a-4c2b-b798-3f4020bbad18
  namespace: kube-system
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&kbver=1.21.0&b=true&s=%2Fdev%2Fsdb%2C%2Fdev%2Fsdc&j=auto&kd=%2Fdev%2Fsdd&c=px-cluster-0276bc75-861a-4c2b-b798-3f4020bbad18&stork=true&st=k8s"
spec:
  image: portworx/oci-monitor:2.7.2
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    devices:
    - /dev/sdb
    journalDevice: auto
    kvdbDevice: /dev/sdc
  network:
    dataInterface: eth1
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "false"
  autopilot:
    enabled: true
  monitoring:
    prometheus:
      enabled: true
      exportMetrics: true

