# SOURCE: https://install.portworx.com/?operator=true&mc=false&kbver=1.21.2&b=true&f=true&j=auto&kd=%2Fdev%2Fsdd&m=eth1&d=eth1&c=px-cluster-6e443718-98b3-46fd-8bdd-4afc554a65e3&stork=true&csi=true&mon=true&st=k8s&promop=true
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-6e443718-98b3-46fd-8bdd-4afc554a65e3
  namespace: kube-system
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&kbver=1.21.2&b=true&f=true&j=auto&kd=%2Fdev%2Fsdd&m=eth1&d=eth1&c=px-cluster-6e443718-98b3-46fd-8bdd-4afc554a65e3&stork=true&csi=true&mon=true&st=k8s&promop=true"
spec:
  image: portworx/oci-monitor:2.8.1.1
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    devices:
    - /dev/sdb
    journalDevice: auto
    kvdbDevice: /dev/sdc
  network:
    dataInterface: eth1
    mgmtInterface: eth1
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "false"
  autopilot:
    enabled: true
    providers:
    - name: default
      type: prometheus
      params:
        url: http://prometheus:9090
  monitoring:
    telemetry:
      enabled: true
    prometheus:
      enabled: true
      exportMetrics: true
  featureGates:
    CSI: "true"
